#Basic configuration
paint-on-overlay = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
vsync = true;
backend = "glx";

# Opacity
inactive-opacity = 0.70;
inactive-opacity-override = false;
#
# fading = true;
# fade-in-step = 0.3;
# fade-out-step = 0.3;

 # animations = ({
 #     triggers = ["open", "close"];
 #     preset = "slide-in";
 #     direction = "down";
 #     duration = 0.1;
 # }, {
 #     triggers = ["show", "hide"];
 #     preset = "appear";
 #     scale = .95;
 #     duration = 0.1;
 # }, {
 #     triggers = ["geometry"];
 #     preset = "geometry-change";
 #     duration = 0.2;
 #     });

#Making i3lock work with rofi
opacity-rule = [
  "100:class_g = 'Polybar' ",
  "10:class_g = 'rofi'",
"90:class_g = 'i3lock'"
];


# Shadows
shadows = false;


blur:
{
  method = "dual_kawase";
  strength = 6;
}

blur-background-exclude = [
    "class_g = 'slop'",
    "class_g = 'rofi'",
    "class_g = 'dmenu'",
];


#Rounding
corner-radius = 0;

rounded-corners-exclude = [
    "bounding_shaped",
    "class_g ='slop'",
    "class_g = 'Polybar'",
    "class_g = 'Rofi'"
];


