#Fonts
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 18
adjust_line_height 115%

disable_ligatures cursor

detect_urls yes
open_url_with default
url_style underline

mouse_hide_wait 2.0
copy_on_select yes

enable_audio_bell no
visual_bell_duration 0

cursor_shape block
cursor_blink_interval 0
cursor_text_color #abided
cursor_trail 1
cursor_trail_decay 0.15 0.25

allow_remote_control socket-only
confirm_os_window_close 0
window_padding_width 0
resize_in_steps yes

repaint_delay 10
input_delay 1
sync_to_monitor yes

env GLFW_IM_MODULE=ibus

map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down
map ctrl+l clear


