#!/usr/bin/env bash
set -euo pipefail

TEMPLATES="$HOME/dev/dev-shells/"

choice=$(
    nix flake show --json "$repo" \
        | jq -r '.templates | keys[]' \
        | sort \
        | fzf --prompt="Template: "
)

[[ -n "$choice" ]]

nix flake init --template "$repo#$choice"
direnv allow

if [[ "$PWD" == "$HOME" ]]; then
    echo "Refusing to initialize git repo in HOME"
    exit 1
fi
git init
git add .
git commit -m "Initial commit"

