#!/usr/bin/env bash

file=$(fd --type f --hidden --follow \
--extension pdf \
--exclude .git \
--exclude .steam \
--exclude .local/share/Steam \
--exclude .wine . 2>/dev/null | fzf)

[ -z "$file" ] && exit 0

zathura -- "$file" >/dev/null 2>&1 &
